[
  {
    name: "Ignite",
    shard: "ignite",
    desc: "",
    ver: "1.0",
    duality: "dark",
    cols: {
      prot: "oklch(69.96% 0.20 44.44)",
      deut: "oklch(86.44% 0.177 93.53)",
      focus: "cyan",
      text: "white",
      "text-prot": "white",
      "text-deut": "white",
      "text-trit": "white",
      "text-bold": "white",
      back: "oklch(10% 0 0)",
      "back-prot": "oklch(10% 0 0)",
      "back-deut": "oklch(20% 0 0)",
      "back-trit": "oklch(30% 0 0)",
      line: "oklch(45% 0 0)",
      "line-prot": "red",
      "line-deut": "red",
      link: "oklch(86.44% 0.177 93.53)",
      "link-hover": "oklch(75.78% 0.1634 70.24)",
      "link-click": "",
      card: "",
      "card-hover": "",
      "card-click": ""
    }
  },
  {
    name: "soup",
    shard: "soup",
    desc: "Light colours for the Assort site",
    ver: "1.0",
    duality: "light",
    cols: {
      prot: "#4090f1",
      deut: "#ff0090",
      hover: "rgba(0 0 0 / 8%)",
      click: "rgba(0 0 0 / 16%)",
      focus: "#40e0ff",
      text: "oklch(1% 0 0)",
      "text-prot": "#204080",
      "text-deut": "oklch(60% 0.0434 269.73)",
      "text-trit": "oklch(80% 0.0434 269.73)",
      back: "oklch(97.5% 0.006 269.73)",
      "back-prot": "",
      "back-deut": "oklch(94.5% 0.006 269.73)",
      "back-trit": "",
      line: "oklch(75% 0.006 269.73)",
      "line-prot": "",
      "line-deut": "",
      link: "#2070c1",
      "link-visit": "#404090",
      "link-hover": "#ff0090",
      "link-click": "#9040f1",
      card: "white",
      "card-hover": "grey",
      "card-click": "darkgrey"
    }
  },
  {
    name: "souper",
    shard: "souper",
    desc: "Dark colours for the Assort site",
    ver: "1.0",
    duality: "dark",
    cols: {
      prot: "",
      deut: "",
      focus: "",
      text: "",
      "text-prot": "",
      "text-deut": "",
      "text-trit": "",
      "text-bold": "",
      back: "",
      "back-prot": "",
      "back-deut": "",
      "back-trit": "",
      line: "",
      "line-prot": "",
      "line-deut": "",
      link: "",
      "link-hover": "",
      "link-click": "",
      card: "",
      "card-hover": "",
      "card-click": ""
    }
  }
]