[
  {
    name: "Ignite",
    shard: "ignite",
    desc: "",
    ver: "1.0",
    duality: "dark",
    cols: {
      prot: "oklch(69.96% 0.20 44.44)",
      deut: "oklch(86.44% 0.177 93.53)",
      focus: "cyan",
      text: "white",
      "text-prot": "white",
      "text-deut": "white",
      "text-trit": "white",
      "text-bold": "white",
      back: "oklch(10% 0 0)",
      "back-prot": "oklch(10% 0 0)",
      "back-deut": "oklch(20% 0 0)",
      "back-trit": "oklch(30% 0 0)",
      line: "oklch(45% 0 0)",
      "line-prot": "red",
      "line-deut": "red",
      link: "oklch(86.44% 0.177 93.53)",
      "link-hover": "oklch(75.78% 0.1634 70.24)",
      "link-click": "",
      card: "",
      "card-hover": "",
      "card-click": ""
    }
  },
  {
    name: "soup",
    shard: "soup",
    desc: "Light colours for the Assort site",
    ver: "1.0",
    duality: "light",
    cols: {
      prot: "",
      deut: "",
      focus: "",
      text: "",
      "text-prot": "",
      "text-deut": "",
      "text-trit": "",
      "text-bold": "",
      back: "",
      "back-prot": "",
      "back-deut": "",
      "back-trit": "",
      line: "",
      "line-prot": "",
      "line-deut": "",
      link: "",
      "link-hover": "",
      "link-click": "",
      card: "",
      "card-hover": "",
      "card-click": ""
    }
  },
  {
    name: "souper",
    shard: "souper",
    desc: "Dark colours for the Assort site",
    ver: "1.0",
    duality: "dark",
    cols: {
      prot: "",
      deut: "",
      focus: "",
      text: "",
      "text-prot": "",
      "text-deut": "",
      "text-trit": "",
      "text-bold": "",
      back: "",
      "back-prot": "",
      "back-deut": "",
      "back-trit": "",
      line: "",
      "line-prot": "",
      "line-deut": "",
      link: "",
      "link-hover": "",
      "link-click": "",
      card: "",
      "card-hover": "",
      "card-click": ""
    }
  }
]