name: Quarkup

on:
  workflow_dispatch:

  push:
    paths:
      - '**.md'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: 'Quarkdown: activate'
        run: |
          curl -L \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.CHARM }}' \
            -H 'X-Github-Api-Version: 2022-11-28' \
            https://api.github.com/repos/Sup2point0/Quarkdown/dispatches \
            -d >
              {
                "event_type": "trigger-workflow",
                "client_payload": {
                  "service": "Assort",
                  "version": "",
                  "unit": false,
                  "integration": true
                }
              }
