name: Quarkup

on:
  workflow_dispatch:

  push:
    paths:
      - '**.md'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: 'Quarkdown: activate'
        run: |
          curl -X POST https://api.github.com/repos/Sup2point0/Quarkdown/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.CHARM }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          
          # curl -L
          # -X POST
          # -H 'Accept: application/vnd.github+json'
          # -H 'Authorization: Bearer ${{ secrets.CHARM }}'
          # -H 'X-GitHub-Api-Version: 2022-11-28'
          # https://api.github.com/repos/Sup2point0/Quarkdown/actions/workflows/assort.yml/dispatch
          
          # curl -XPOST
          # -u 'Sup2point0:${{secrets.PAT_TOKEN}}'
          # -H 'Accept: application/vnd.github.everest-preview+json'
          # -H 'Content-Type: application/json'
          # https://api.github.com/repos/Sup2point0/Quarkdown/actions/workflows/assort.yaml/dispatches --data '{"ref": "main"}'
